version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Collect first logcat log
          background: true
          command: |
            tail -f "/var/log/dpkg.log" & sleep 1m
            circleci-agent step halt
      - run:
          name: Collect second logcat log
          background: true
          command: |
            sleep 1m
            tail -f "/var/log/dpkg.log" & sleep 1m
            circleci-agent step halt
      - run:
          name: Collect final logcat log
          background: true
          command: |
            sleep 2m
            tail -f "/var/log/dpkg.log"
      - run: sleep 30

workflows:
  workflow:
    jobs:
    - build
